# .gitlab-ci.yml

linux build:
  script: sleep 10 && echo Done

mac build:
  script: sleep 20 && echo Done

lint:
  needs: []
  script: echo Done

linux unit tests:
  needs:
    - linux build
  script: echo Done

linux e2e tests:
  needs:
    - linux build
  script: sleep 10 && echo Done

mac unit tests:
  needs:
    - mac build
  script: sleep 5 && echo Done

mac e2e tests:
  needs:
    - mac build
  script: sleep 30 && echo Done

release linux:
  script: "echo Done"
  needs:
    - lint
    - linux unit tests
    - linux e2e tests

release mac:
  script: "echo Done"
  needs:
    - lint
    - mac unit tests
    - mac e2e tests
