foo:
  script: echo foo build ...
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: "$CI_PIPELINE_SOURCE"

bar:
  script: echo bar build ...
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"

baz:
  script: echo xxxc
