# .gitlab-ci.yml

stages:
  - build
  - test

build html:
  stage: build
  script:
    - mkdir -p out
    - echo '<h1>Hello World!</h1>' > out/index.html
  artifacts:
    paths:
      - out

test html:
  stage: test
  script:
    - cat out/index.html


build go:
  stage: build
  image: golang:1.19
  script:
    - go build hello.go
  artifacts:
    paths:
      - hello

test go:
  stage: test
  script:
    - ./hello